CREATE TABLE "members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "fullname" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "plan" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "expired_at" timestamp NOT NULL,
  "auto_renew" boolean NOT NULL
);

CREATE TABLE "items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "amount" integer NOT NULL,
  "price" integer NOT NULL
);

CREATE TABLE "entries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" integer NOT NULL,
  "total" integer NOT NULL,
  "created_at" timestamp NOT NULL,
  "item_id" integer NOT NULL
);

COMMENT ON COLUMN "items"."price" IS 'cent unit';

COMMENT ON COLUMN "entries"."total" IS 'cent unit';
