// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: email.sql

package db

import (
	"context"
)

const createVerificationEmail = `-- name: CreateVerificationEmail :one
INSERT INTO verification_emails(
  member_id, email, secret_code
) VALUES (
  $1, $2, $3
) RETURNING id, member_id, email, secret_code
`

type CreateVerificationEmailParams struct {
	MemberID   int32  `json:"member_id"`
	Email      string `json:"email"`
	SecretCode string `json:"secret_code"`
}

func (q *Queries) CreateVerificationEmail(ctx context.Context, arg CreateVerificationEmailParams) (VerificationEmail, error) {
	row := q.db.QueryRowContext(ctx, createVerificationEmail, arg.MemberID, arg.Email, arg.SecretCode)
	var i VerificationEmail
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Email,
		&i.SecretCode,
	)
	return i, err
}
