// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Entry struct {
	ID       int32 `json:"id"`
	MemberID int32 `json:"member_id"`
	ItemID   int32 `json:"item_id"`
	Quantity int32 `json:"quantity"`
	// cent unit
	Total     int32     `json:"total"`
	CreatedAt time.Time `json:"created_at"`
}

type Item struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Quantity int32  `json:"quantity"`
	// cent unit
	Price int32 `json:"price"`
}

type Member struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Fullname  string    `json:"fullname"`
	Email     string    `json:"email"`
	Plan      int32     `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
	ExpiredAt time.Time `json:"expired_at"`
	AutoRenew bool      `json:"auto_renew"`
}
